add function shouldShowXLevelIcon()
causes error

frameworks/base/packages/SettingsLib/src/com/android/settingslib/wifi/WifiEntryPreference.java:140: error: cannot find symbol
        final boolean showX = mWifiEntry.shouldShowXLevelIcon();
                                        ^
  symbol:   method shouldShowXLevelIcon()
  location: variable mWifiEntry of type WifiEntry